
require('./assets/llj/assets/script/setbuttom');
require('./assets/llj/assets/script/switchbutton');
require('./assets/scripts/0 - 001');
require('./assets/scripts/0 - 002');
require('./assets/scripts/0 - 003');
require('./assets/scripts/0 - 004');
require('./assets/scripts/0 - 005');
require('./assets/scripts/0 - 006');
require('./assets/scripts/0 - 007');
require('./assets/scripts/0 - 008');
require('./assets/scripts/0 - 009');
require('./assets/scripts/0 - 010');
require('./assets/scripts/0 - 011');
require('./assets/scripts/0 - 012');
require('./assets/scripts/0 - 013');
require('./assets/scripts/0 - 014');
require('./assets/scripts/0 - 015');
require('./assets/scripts/0');
require('./assets/scripts/bag/bagSetting');
require('./assets/scripts/bag/bagTool');
require('./assets/scripts/bag/useTool');
require('./assets/scripts/bglockctr');
require('./assets/scripts/button');
require('./assets/scripts/changeback');
require('./assets/scripts/checkbutton');
require('./assets/scripts/chengctr');
require('./assets/scripts/controller/camera');
require('./assets/scripts/controller/changeScene');
require('./assets/scripts/controller/game - 001');
require('./assets/scripts/controller/loadState');
require('./assets/scripts/controller/player_ctrl_pc - 001');
require('./assets/scripts/controller/saveState');
require('./assets/scripts/dialog/dialog - 001');
require('./assets/scripts/game_chp1/cp1_cup/1_java');
require('./assets/scripts/game_chp1/cp1_cup/2_java');
require('./assets/scripts/game_chp1/cp1_cup/3_java');
require('./assets/scripts/game_chp1/cp1_cup/4_java');
require('./assets/scripts/game_chp1/cp1_cup/5_java');
require('./assets/scripts/game_chp1/cp1_lamp/setbuttom');
require('./assets/scripts/game_chp1/cp1_lamp/switchbutton');
require('./assets/scripts/game_chp1/cp1_washingMachine/button');
require('./assets/scripts/game_chp1/cp1_washingMachine/changcolor');
require('./assets/scripts/game_chp1/cp1_washingMachine/check');
require('./assets/scripts/game_chp1/cp1_washingMachine/check_out');
require('./assets/scripts/game_chp1/cp1_washingMachine/config');
require('./assets/scripts/games/gameController');
require('./assets/scripts/info/ItemInfo');
require('./assets/scripts/info/bagInfo');
require('./assets/scripts/info/dialogContent');
require('./assets/scripts/info/gameInfo');
require('./assets/scripts/info/sceneinfo');
require('./assets/scripts/item/item');
require('./assets/scripts/kitchenctr');
require('./assets/scripts/lockctr');
require('./assets/scripts/paperctr');
require('./assets/scripts/savestate');
require('./assets/scripts/showbutton');
require('./assets/scripts/stairlock');
require('./assets/scripts/testbutton');
require('./assets/scripts/tip/tips');
require('./assets/scripts/tip/trigger');
require('./assets/scripts/tool/tool');
require('./assets/scripts/zdctr');
